### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by igitur** [igitur/WPF.ListViewLayoutManager#1]
Hi @Giannoudis 

This is a courtesy request whether I can take your code at https://www.codeproject.com/Articles/25058/ListView-Layout-Manager and redistribute it here on Github under the MIT license. It seems to be compatible with the CPOL license on CodeProject. I don't plan to do much development on this library other than package it on NuGet. I would appreciate it if you could approve this request.

Thanks

**Comment by ghost** [comment]
Hi @igitur 

Many thanks for your support.
Sure, you can use the source code of the ListView Layout Manager to redistribute it on GitHub and NuGet using the MIT license.

Regards

**Comment by igitur** [comment]
Thank you
